Repository vaticle/typedb-examples, pull requests merged in 2019-05, with the labels that each got.

#55 Minor update for Python 3 compatibility for Tube Example
  tube_network/README.md
  tube_network/src/app.py
Labels: bug

#58 Add BioGrakn Repo section in README
  README.md
Labels: feature

#61 phone_calls: replace is-customer with negation
  phone_calls/java/CSVMigration.java
  phone_calls/java/JSONMigration.java
  phone_calls/java/Queries.java
  phone_calls/java/XMLMigration.java
  phone_calls/nodejs/migrateCsv.js
  phone_calls/nodejs/migrateJson.js
  phone_calls/nodejs/migrateXml.js
  phone_calls/nodejs/package.json
  phone_calls/nodejs/queries.js
  phone_calls/python/migrate_csv.py
  phone_calls/python/migrate_json.py
  phone_calls/python/migrate_xml.py
  phone_calls/python/queries.py
  schemas/phone-calls-schema.gql
Labels: feature, refactor

#57 Removes duplicate applications/tube_network
  applications/tube_network/__init__.py
  applications/tube_network/src/__init__.py
  applications/tube_network/src/download_dataset.py
  applications/tube_network/src/journey_planner.py
Labels: bug

#64 Fix CI by synchronizing .bazelrc with @graknlabs_build_tools
  .bazelrc
  README.md
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build
